insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Carlee', 'Leport', 'Camier', '31-097-1001', 'ccamier0@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Adelle', 'Gounin', 'Petrusch', '12-521-2489', 'apetrusch1@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Gussy', 'Blacklawe', 'Grishkov', '98-283-6020', 'ggrishkov2@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Clywd', 'Crockett', 'Mingey', '82-299-2781', 'cmingey3@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Barde', 'Brassill', null, '53-012-8498', 'btoleman4@friendfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Hinda', 'Atthow', 'Bruhn', '46-321-9245', 'hbruhn5@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Paulie', 'Mateu', 'Simeonov', '49-450-9753', 'psimeonov6@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Nick', 'Nolda', 'Lawrenz', '86-946-3641', 'nlawrenz7@sun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Ezekiel', 'Cuckoo', null, '70-172-0906', 'ebradford8@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Arleyne', 'Croce', 'McGlade', '23-581-1706', 'amcglade9@google.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Shaylynn', 'MacGovern', 'Ritch', '57-597-8308', 'sritcha@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Kippie', 'Cleeve', 'Lutwyche', '68-351-0579', 'klutwycheb@disqus.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Fritz', 'Absolom', 'Le Brun', '24-118-7374', 'flebrunc@icq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Ulrike', 'McIan', 'Presho', '93-680-1087', 'upreshod@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Mitzi', 'Wrathall', 'Tewelson', '15-008-1272', 'mtewelsone@phpbb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Karlie', 'O''Donohue', 'Defau', '94-585-2587', 'kdefauf@independent.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Duffie', 'Howsan', 'Philpin', '05-492-7412', 'dphilping@dropbox.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Leonard', 'Gipp', 'Balffye', '54-706-4478', 'lbalffyeh@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Arluene', 'Astley', 'Orgel', '84-648-7178', 'aorgeli@wordpress.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Mickie', 'Headan', 'Pristnor', '09-932-9767', 'mpristnorj@trellian.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Lawry', 'Sweetland', 'Pohling', '89-384-3675', 'lpohlingk@gnu.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Billy', 'Trounce', 'Brendish', '45-854-3622', 'bbrendishl@sogou.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Lonna', 'Brodnecke', 'Gurery', '51-284-6498', 'lgurerym@creativecommons.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Leonard', 'Fearneley', 'McWhannel', '82-141-5053', 'lmcwhanneln@spotify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Isa', 'Brisley', 'Giottoi', '99-757-8897', 'igiottoio@cyberchimps.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Fidelity', 'Ell', 'Posnette', '06-095-3703', 'fposnettep@ucla.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Reena', 'Chappelow', 'Fackney', '14-983-6132', 'rfackneyq@umn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Mirella', 'Ivanikov', 'McTrustram', '63-297-0450', 'mmctrustramr@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Shawnee', 'Saines', 'Vala', '94-558-8656', 'svalas@nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Cammy', 'Keates', null, '44-889-9247', 'cherleyt@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Delaney', 'Vallentine', 'Fautley', '59-722-4253', 'dfautleyu@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Dyane', 'Mulderrig', 'Yellop', '47-298-6193', 'dyellopv@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'Ali', 'Orridge', 'Gilburt', '01-787-0807', 'agilburtw@patch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Ruddie', 'Deacon', 'Emslie', '07-154-9750', 'remsliex@youku.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Shem', 'Alessandrelli', null, '68-492-7160', 'sbeebisy@ucla.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Lyle', 'Forseith', null, '96-085-8269', 'labbeyz@uol.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Benedikta', 'Whewill', 'Byer', '06-356-4928', 'bbyer10@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Olag', 'Yude', 'Escale', '63-775-5489', 'oescale11@sohu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Susy', 'Brewitt', 'Hearons', '72-101-8089', 'shearons12@narod.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Bobbye', 'Arber', 'Hearnshaw', '73-262-9297', 'bhearnshaw13@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Regen', 'Bigg', 'Doust', '94-035-6047', 'rdoust14@abc.net.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Cammi', 'Coronas', 'Jordin', '76-903-1368', 'cjordin15@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Lind', 'MacKeig', 'Britney', '57-989-0104', 'lbritney16@fc2.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Hussein', 'Pullin', 'Littler', '48-838-3686', 'hlittler17@fema.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Fonsie', 'Usher', 'Mirfield', '87-432-6031', 'fmirfield18@disqus.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Blondelle', 'Bothram', 'McUre', '04-598-7053', 'bmcure19@paginegialle.it', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Mandi', 'Grew', 'Greeson', '48-167-0922', 'mgreeson1a@zimbio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'Elisha', 'Thirlaway', 'Coomes', '01-816-1846', 'ecoomes1b@time.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Essa', 'de Lloyd', 'Greenaway', '63-306-8346', 'egreenaway1c@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Jule', 'Standingford', 'Lloyd-Williams', '32-113-2937', 'jlloydwilliams1d@myspace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Alethea', 'Ridout', 'Corrigan', '64-269-9815', 'acorrigan1e@deviantart.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Maryl', 'Lardeur', 'Logesdale', '34-441-6084', 'mlogesdale1f@shinystat.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Walliw', 'Barrington', 'Spreckley', '46-232-8010', 'wspreckley1g@blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Amelita', 'Puttergill', 'Le Floch', '18-610-5057', 'alefloch1h@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Dell', 'Nesey', 'Pettis', '85-847-7527', 'dpettis1i@irs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Mavis', 'Brugmann', 'Whitehorne', '03-624-2583', 'mwhitehorne1j@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Aubrie', 'Dunstall', 'Sebring', '53-768-2302', 'asebring1k@qq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Bogart', 'Greer', 'O''Lenechan', '51-562-1530', 'bolenechan1l@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Britney', 'Harbinson', 'Owenson', '50-499-1515', 'bowenson1m@dyndns.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Kacy', 'Banisch', 'Lux', '63-724-6103', 'klux1n@yolasite.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Starlin', 'Duplan', 'Cookson', '31-066-3747', 'scookson1o@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Eachelle', 'Solomonides', 'Cothey', '07-173-4812', 'ecothey1p@economist.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Reinaldo', 'Corsan', 'Croan', '40-300-5447', 'rcroan1q@friendfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Clemmy', 'Zavattari', 'Etherson', '59-669-6610', 'cetherson1r@i2i.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Yvon', 'Dooland', 'Stryde', '09-109-4185', 'ystryde1s@umn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Persis', 'Johnstone', 'Rubertis', '42-098-6544', 'prubertis1t@hatena.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Silvie', 'Chadburn', 'Shorto', '50-045-4926', 'sshorto1u@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Eleanor', 'Bloxsom', null, '57-920-7340', 'eholtum1v@is.gd', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Daniella', 'McWhin', 'Abisetti', '82-042-2459', 'dabisetti1w@people.com.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Crawford', 'Carme', 'Eustanch', '09-879-0600', 'ceustanch1x@nytimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Tuckie', 'Harrie', 'Lyvon', '93-183-2846', 'tlyvon1y@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Aurlie', 'Brotherhed', 'Fernehough', '85-652-7042', 'afernehough1z@census.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Cheri', 'Dockery', null, '99-117-1877', 'cgrissett20@example.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Silas', 'Harness', 'Howsden', '09-562-5458', 'showsden21@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Trish', 'Asaaf', 'Edger', '34-815-5165', 'tedger22@addtoany.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Daniella', 'Beckhurst', 'Feldmus', '68-868-7222', 'dfeldmus23@behance.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Jay', 'Du Pre', 'Duckitt', '81-531-5127', 'jduckitt24@time.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Lorette', 'Miche', 'Eirwin', '19-982-1125', 'leirwin25@ustream.tv', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Xaviera', 'Filov', 'Phillimore', '57-108-6686', 'xphillimore26@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Dru', 'Clausewitz', null, '70-904-3179', 'drozycki27@stanford.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Faith', 'Tooth', 'Schirak', '90-188-1645', 'fschirak28@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Hetty', 'Chinn', 'Belverstone', '83-929-1262', 'hbelverstone29@cafepress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Gunner', 'Huard', null, '89-372-7328', 'gcess2a@exblog.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Timi', 'Feldhuhn', 'Hodgen', '21-039-7567', 'thodgen2b@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Lenka', 'De Malchar', 'Braisted', '47-931-3869', 'lbraisted2c@163.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Suzy', 'Millott', 'Harker', '88-939-3420', 'sharker2d@yellowbook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Hedi', 'Landells', null, '80-652-9196', 'hrobard2e@woothemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Susie', 'Antrack', null, '80-607-1601', 'spendreigh2f@salon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Joyce', 'Straneo', 'Jacketts', '46-220-4795', 'jjacketts2g@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Ferrell', 'Roan', null, '27-170-0840', 'ftrudgeon2h@state.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Sayer', 'Danhel', null, '03-627-4273', 'sjahnel2i@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Elyn', 'Baumer', 'Critch', '91-299-3179', 'ecritch2j@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Anselm', 'Shinfield', 'Goggan', '17-851-3491', 'agoggan2k@discuz.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Artie', 'Warke', 'Wann', '04-814-2658', 'awann2l@livejournal.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Marylee', 'Iddins', 'Labroue', '12-529-0052', 'mlabroue2m@blogger.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Tiffani', 'Gulley', 'Willisch', '86-588-9862', 'twillisch2n@japanpost.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Janeczka', 'Matuszynski', 'Ridsdell', '05-941-6317', 'jridsdell2o@nps.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Gaven', 'Jakubowicz', null, '50-865-3144', 'gpaolicchi2p@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Aeriel', 'Edleston', 'Jacquet', '80-382-0821', 'ajacquet2q@blinklist.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Tabb', 'Priestley', 'Willingham', '30-493-8128', 'twillingham2r@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Emmalynne', 'Glisane', 'Flaunders', '09-483-4238', 'eflaunders2s@google.com.hk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Falito', 'Turfin', 'Blacksell', '35-339-1510', 'fblacksell2t@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Lethia', 'Tweedie', 'Maryan', '59-533-8070', 'lmaryan2u@clickbank.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Leonidas', 'Lowther', null, '62-102-0265', 'lkenworthey2v@godaddy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Jessamyn', 'Foker', null, '14-246-5063', 'jkermitt2w@go.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Pearline', 'Heffron', 'Randle', '97-082-9154', 'prandle2x@pen.io', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Kit', 'Dive', 'O''Keenan', '53-434-1717', 'kokeenan2y@opera.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Cybill', 'Gheorghe', 'Matiasek', '16-355-7027', 'cmatiasek2z@dropbox.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Nicole', 'Racher', 'Oxherd', '01-013-0127', 'noxherd30@sciencedaily.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Gradeigh', 'Geaveny', null, '55-651-4649', 'goganesian31@goo.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Laural', 'Gwinnel', 'Slight', '82-910-0018', 'lslight32@list-manage.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Aluino', 'Goldfinch', 'Keig', '12-092-1140', 'akeig33@skype.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Natalie', 'Warwicker', 'Gulliver', '33-276-9347', 'ngulliver34@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Gabi', 'Ivanchikov', 'Olivera', '76-596-5590', 'golivera35@ox.ac.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Erasmus', 'Canet', 'Norree', '41-889-9192', 'enorree36@youku.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Breena', 'Whitwam', 'Cofax', '49-901-6299', 'bcofax37@buzzfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Jania', 'Radwell', 'Crossman', '38-655-6720', 'jcrossman38@arizona.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Bekki', 'Willoughley', 'Episcopio', '39-289-6153', 'bepiscopio39@earthlink.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Robinette', 'O''Fallone', 'Preedy', '30-304-4212', 'rpreedy3a@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Ken', 'Brushneen', 'Nunan', '29-833-4755', 'knunan3b@yandex.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Curr', 'Leech', null, '61-687-1540', 'ccrum3c@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Mavis', 'Consterdine', 'Allitt', '14-085-8649', 'mallitt3d@google.com.hk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Nerta', 'Wyles', 'Favey', '19-347-1824', 'nfavey3e@usnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Silvester', 'Corringham', 'Philpault', '01-960-7010', 'sphilpault3f@4shared.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Shalne', 'Gowlett', null, '89-569-2819', 'sscargle3g@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Padraig', 'McSkeagan', 'Sneesbie', '74-519-8519', 'psneesbie3h@youtube.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Gustave', 'Duly', 'Kristoffersen', '08-674-0708', 'gkristoffersen3i@alexa.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Nollie', 'Cowburn', 'Ciccone', '02-045-1390', 'nciccone3j@sfgate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Beltran', 'Casely', 'Bevir', '18-215-2974', 'bbevir3k@1und1.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Skyler', 'Baudino', 'Collar', '59-145-2969', 'scollar3l@indiegogo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Tobye', 'Pendry', 'Ranson', '86-371-5312', 'transon3m@blogger.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Kele', 'Cuseick', null, '88-512-5176', 'kfrance3n@fda.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Hendrik', 'Drewery', 'Shovell', '78-609-5799', 'hshovell3o@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Ari', 'Grewe', 'Howell', '06-765-1658', 'ahowell3p@google.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Kaitlynn', 'Harnell', null, '31-219-0063', 'kabrahamson3q@wordpress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Zabrina', 'Bownde', 'Allbon', '34-979-9923', 'zallbon3r@hatena.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Shara', 'Tigwell', null, '02-307-9737', 'solivie3s@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Sandra', 'Assante', 'Woolam', '40-709-8983', 'swoolam3t@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Gilberta', 'Shurrocks', 'Yukhnov', '97-118-7991', 'gyukhnov3u@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Nahum', 'Novic', 'Morfey', '06-176-2465', 'nmorfey3v@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Nickolas', 'Burbidge', 'Tuffey', '34-387-3430', 'ntuffey3w@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Gert', 'Grosvenor', null, '23-179-5868', 'gmcisaac3x@unicef.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Zane', 'Woodington', null, '27-350-5606', 'zantunez3y@nifty.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Roosevelt', 'Asquez', 'Bausor', '58-181-7098', 'rbausor3z@dmoz.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Kaitlynn', 'Outright', 'Jorin', '44-833-0898', 'kjorin40@blogspot.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Gray', 'Jearum', 'Bentick', '54-114-2484', 'gbentick41@springer.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Mabel', 'Rohfsen', null, '72-646-6281', 'mcoppeard42@liveinternet.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Annissa', 'Mattielli', 'Rees', '72-073-2325', 'arees43@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Delcina', 'McIlmorow', 'Blasik', '48-949-6757', 'dblasik44@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Moritz', 'Crimp', 'Bouchard', '06-146-2193', 'mbouchard45@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Pavia', 'Sambeck', 'Larner', '99-593-8245', 'plarner46@wp.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Olva', 'Fines', 'Filipic', '02-195-5564', 'ofilipic47@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Verine', 'Paladino', 'Georgeot', '18-815-8419', 'vgeorgeot48@reference.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Kellby', 'Tootin', 'Butland', '75-333-8102', 'kbutland49@state.tx.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Thalia', 'Merali', 'Caughtry', '72-262-3528', 'tcaughtry4a@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Herschel', 'Handmore', 'Hodgen', '85-821-3178', 'hhodgen4b@alexa.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Leese', 'Oatley', null, '90-203-7060', 'lstoffels4c@cnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Merrick', 'Gregoraci', 'McCartan', '70-568-2723', 'mmccartan4d@soup.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Lenore', 'Vlasenkov', 'Hambrook', '91-857-0694', 'lhambrook4e@guardian.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Ken', 'Jeskins', 'Fosbraey', '77-297-2226', 'kfosbraey4f@jalbum.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Rose', 'Oxnam', 'Boath', '67-031-0238', 'rboath4g@ask.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Franciskus', 'Collum', 'Stickels', '09-260-8542', 'fstickels4h@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Ninnetta', 'Kelland', 'Doerrling', '93-589-5980', 'ndoerrling4i@baidu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Nicola', 'Gittus', 'Jaulmes', '51-641-3473', 'njaulmes4j@weather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Darbie', 'Priddis', 'Sarten', '41-508-7541', 'dsarten4k@stanford.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Regan', 'Rosenfeld', null, '36-140-5849', 'rjeandon4l@opera.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Eryn', 'Berks', 'Jealous', '64-929-6638', 'ejealous4m@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Bellanca', 'Loram', null, '29-452-8057', 'bdrackford4n@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Lillian', 'Glentworth', 'Ferebee', '88-475-9791', 'lferebee4o@unicef.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Tina', 'Diboll', 'Filson', '11-486-0071', 'tfilson4p@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Perceval', 'Puttrell', null, '15-521-8924', 'pburgise4q@umn.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Morrie', 'Stucke', 'Ellison', '30-212-8563', 'mellison4r@illinois.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Jackie', 'Fradson', null, '67-823-1555', 'jrobrow4s@jimdo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Elvyn', 'Babe', 'Jumonet', '95-701-2477', 'ejumonet4t@domainmarket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Vitia', 'Emer', 'Ricarde', '16-355-4058', 'vricarde4u@tinyurl.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Cynde', 'Moran', 'Ballinghall', '70-845-1299', 'cballinghall4v@huffingtonpost.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Wilhelm', 'Henke', 'Hendrikse', '56-390-3417', 'whendrikse4w@about.me', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Tomasina', 'Inglefield', 'Lyste', '45-185-1645', 'tlyste4x@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Ethelda', 'Tinghill', 'Gidley', '92-216-0380', 'egidley4y@cmu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Rozele', 'Killshaw', 'Tobias', '75-840-0696', 'rtobias4z@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Witty', 'Meighan', null, '88-136-7846', 'walbin50@rakuten.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Marleah', 'Wehner', 'McGrudder', '94-159-7453', 'mmcgrudder51@washington.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Curt', 'Walden', null, '29-101-7730', 'ccaldecutt52@nsw.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Saleem', 'Shafe', 'Trethowan', '17-038-6391', 'strethowan53@privacy.gov.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Addie', 'Satford', 'Marieton', '55-299-3256', 'amarieton54@mysql.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Del', 'Surguine', 'Guiraud', '70-375-0889', 'dguiraud55@patch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Basil', 'Gaye', null, '63-593-7081', 'bdederich56@house.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Cori', 'Gealle', 'Willmetts', '82-194-5400', 'cwillmetts57@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Brodie', 'Shoreson', 'Davidek', '39-124-7190', 'bdavidek58@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Simonne', 'Vanetti', null, '31-993-6302', 'sjaquiss59@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Godfrey', 'Bloodworth', 'Astill', '00-308-1206', 'gastill5a@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Norman', 'Swait', 'Sulman', '81-147-3924', 'nsulman5b@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Emyle', 'Raycroft', 'Shuttleworth', '27-856-8745', 'eshuttleworth5c@umich.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Travus', 'Lysaght', 'Foakes', '57-716-3267', 'tfoakes5d@t-online.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Indira', 'Kynforth', 'Alesi', '62-714-9802', 'ialesi5e@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Fanechka', 'Mustard', 'Bodle', '47-531-2265', 'fbodle5f@epa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Cari', 'Barlie', null, '50-269-6574', 'cpaget5g@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Iggy', 'Beacham', 'Billin', '77-083-2252', 'ibillin5h@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Alika', 'Mercik', null, '96-836-0350', 'athorn5i@weibo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Ibbie', 'Readshaw', null, '45-531-3916', 'istorey5j@moonfruit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Louella', 'Lichtfoth', 'Ortell', '00-941-1139', 'lortell5k@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Bevan', 'Exeter', 'Muck', '39-127-0763', 'bmuck5l@oakley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Dayle', 'Rimmer', null, '61-599-2964', 'dfallow5m@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Colas', 'Coie', 'Quare', '31-655-4661', 'cquare5n@marketwatch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Trina', 'Killerby', 'Varden', '90-103-9894', 'tvarden5o@deliciousdays.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Cletus', 'McCrae', 'Ison', '18-922-8327', 'cison5p@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Marje', 'Woolfenden', 'Bastow', '93-907-0270', 'mbastow5q@ted.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Stepha', 'Lumber', 'Reeveley', '76-678-8129', 'sreeveley5r@list-manage.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Casper', 'Clemoes', null, '85-097-7923', 'clarby5s@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Jazmin', 'Jochen', 'Blincoe', '03-798-8588', 'jblincoe5t@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Tirrell', 'Fairholme', null, '40-912-1949', 'ttrymme5u@altervista.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Launce', 'Eliaz', 'Pudner', '30-160-9126', 'lpudner5v@qq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Bryn', 'Laughlin', null, '97-925-7110', 'babramov5w@irs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Mattie', 'Salzberger', 'Jeffs', '35-106-9034', 'mjeffs5x@soundcloud.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'Amil', 'Beckers', null, '06-106-9217', 'apine5y@census.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Kermy', 'Sealy', 'Fairney', '53-745-3461', 'kfairney5z@g.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Carmelia', 'Kindall', 'Eskrigge', '53-218-8830', 'ceskrigge60@ebay.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Manda', 'Vuitte', null, '07-571-7367', 'mtabram61@sciencedirect.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Esmaria', 'Acosta', 'Aldine', '07-453-2576', 'ealdine62@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Xavier', 'Siaskowski', 'Carme', '18-469-4206', 'xcarme63@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Curt', 'Cobleigh', null, '78-868-5299', 'cbalasini64@flavors.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Selia', 'McCrae', null, '07-104-1464', 'smacconachy65@yellowbook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Merv', 'Castelletti', null, '20-292-2427', 'mivett66@time.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Oriana', 'Kivelhan', 'Brisland', '23-561-5212', 'obrisland67@parallels.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Katey', 'Ackeroyd', 'Berry', '92-499-0457', 'kberry68@adobe.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Wilden', 'Brient', 'Graves', '96-628-9828', 'wgraves69@sbwire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Haslett', 'Archdeacon', 'McFee', '29-870-3164', 'hmcfee6a@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Alley', 'Quig', 'Penbarthy', '79-857-2589', 'apenbarthy6b@wix.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Ophelie', 'Ibbs', 'Joiris', '55-946-9122', 'ojoiris6c@icq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Ricky', 'Kopmann', 'Gurwood', '20-187-1527', 'rgurwood6d@blogger.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Adlai', 'Klemke', 'Vannuccinii', '73-817-3435', 'avannuccinii6e@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Gustaf', 'Markl', 'Cornick', '35-235-8575', 'gcornick6f@wufoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Cristen', 'Ballsdon', 'Atte-Stone', '79-675-7867', 'cattestone6g@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Lars', 'Svanini', 'Conerding', '27-783-7527', 'lconerding6h@biglobe.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Farrah', 'Ollander', 'Trathan', '61-814-2096', 'ftrathan6i@t-online.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Roscoe', 'Wallsworth', null, '62-616-9192', 'rmonshall6j@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Lutero', 'Wilcock', 'Kenion', '63-511-6329', 'lkenion6k@indiegogo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Olav', 'Creevy', null, '44-958-8135', 'omonery6l@hubpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Bettine', 'Jedrzej', 'Verson', '99-952-6722', 'bverson6m@gmpg.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Alfonse', 'Eich', 'Crips', '63-361-3764', 'acrips6n@discuz.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Daryle', 'Trowell', 'Hurche', '28-925-3552', 'dhurche6o@microsoft.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Breena', 'Braxay', 'Stretton', '15-642-9745', 'bstretton6p@oaic.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Marijo', 'Reveland', 'Rabjohn', '51-248-1758', 'mrabjohn6q@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Morrie', 'Brigginshaw', null, '19-379-5146', 'mportugal6r@aol.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Arlen', 'Reynalds', null, '43-299-3605', 'amenham6s@photobucket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Maddy', 'Roocroft', 'Faas', '63-976-5911', 'mfaas6t@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Al', 'Alvey', 'McClune', '18-396-8080', 'amcclune6u@symantec.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Jessee', 'Befroy', 'Guard', '70-363-7820', 'jguard6v@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Josefa', 'Hunter', 'Scollick', '66-274-9296', 'jscollick6w@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Eolande', 'McGaw', null, '68-346-1842', 'emyrtle6x@odnoklassniki.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Ophelia', 'Faulds', 'Brownbill', '65-332-4694', 'obrownbill6y@sourceforge.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Drud', 'Tregiddo', 'Trevithick', '33-200-7063', 'dtrevithick6z@php.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Dasi', 'Bettanay', 'Audas', '81-242-5470', 'daudas70@theatlantic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Lynnett', 'Zoppo', 'Kolinsky', '50-293-4791', 'lkolinsky71@pbs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Jere', 'Murden', 'Tonbye', '84-349-5139', 'jtonbye72@prlog.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Abbye', 'Rodda', 'Winchcum', '72-593-0732', 'awinchcum73@imgur.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Augustine', 'Philson', null, '98-994-0196', 'apilbury74@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Jacobo', 'Hallwell', 'Stoller', '75-221-5362', 'jstoller75@springer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Kelsy', 'Grierson', null, '28-537-0043', 'kguiot76@bluehost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Dreddy', 'Rattenbury', null, '58-285-7941', 'dblacker77@mysql.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Pattie', 'Osmar', 'Desvignes', '67-153-1120', 'pdesvignes78@privacy.gov.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Karim', 'Bromwich', 'Mansuer', '13-015-5228', 'kmansuer79@yandex.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Lorrie', 'Tompkin', 'Dreghorn', '15-902-3992', 'ldreghorn7a@gizmodo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Cornelius', 'Mathias', 'Saunton', '08-515-3775', 'csaunton7b@smugmug.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Nester', 'Pryke', null, '84-474-5109', 'ncortin7c@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Scarface', 'Dyball', 'Blincow', '25-711-8269', 'sblincow7d@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Candy', 'Knoller', 'Cumberledge', '68-627-1662', 'ccumberledge7e@51.la', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Amitie', 'Brussels', 'Kanter', '21-612-6961', 'akanter7f@google.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Mendie', 'Tydd', 'Patesel', '91-783-3959', 'mpatesel7g@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Willie', 'McTavish', 'Shaves', '53-347-5564', 'wshaves7h@163.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Dasi', 'Loy', 'Milam', '64-208-1344', 'dmilam7i@ftc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Crista', 'Tinmouth', 'Thalmann', '12-930-8800', 'cthalmann7j@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Melitta', 'Mullender', 'Eamer', '15-485-6502', 'meamer7k@shinystat.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Johann', 'Dany', 'Baytrop', '12-501-9413', 'jbaytrop7l@chron.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Darcey', 'Tattersfield', 'Halle', '16-083-6506', 'dhalle7m@illinois.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Denna', 'McInerney', null, '90-065-8390', 'debourne7n@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Eve', 'Garaway', 'Gleadle', '40-746-5350', 'egleadle7o@netvibes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Colby', 'Golder', 'Fredi', '31-826-0638', 'cfredi7p@de.vu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Casar', 'Ivett', null, '34-964-6894', 'cfarriar7q@aboutads.info', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Freddie', 'Turpey', 'Drewell', '87-388-1778', 'fdrewell7r@biglobe.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Basil', 'Colisbe', null, '10-385-0123', 'bkubacki7s@amazon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Sidoney', 'Tills', 'Franz', '55-435-8395', 'sfranz7t@angelfire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Bess', 'Beaument', 'Sparling', '67-227-6058', 'bsparling7u@t.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Gaylord', 'Worsfold', 'Impett', '03-022-9476', 'gimpett7v@dmoz.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Rona', 'Fenkel', null, '71-589-6768', 'rdregan7w@bizjournals.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Shadow', 'Yeoland', 'Bridat', '95-916-3364', 'sbridat7x@about.me', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Cherri', 'Boxer', 'Artrick', '50-576-7105', 'cartrick7y@businessweek.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Andres', 'A''Barrow', null, '90-408-7658', 'amarquet7z@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Konstantine', 'Kupper', null, '83-349-7775', 'kswindle80@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Jenica', 'Balsellie', 'Gottelier', '78-782-0540', 'jgottelier81@noaa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Benjy', 'Lucas', 'Jedrzaszkiewicz', '95-608-3384', 'bjedrzaszkiewicz82@google.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Regina', 'D''Hooghe', 'Cowlam', '49-422-9937', 'rcowlam83@drupal.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Brunhilda', 'Barkaway', 'Bullin', '54-006-3853', 'bbullin84@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Juana', 'McCaghan', null, '93-409-5405', 'jraw85@discovery.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'Gar', 'Giraux', 'Leathes', '43-802-8336', 'gleathes86@unc.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Gasparo', 'Dalrymple', 'Dunham', '42-620-9684', 'gdunham87@opera.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Ava', 'Bendixen', 'Hardwell', '32-706-4856', 'ahardwell88@apache.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Belva', 'Kuller', null, '34-805-2289', 'bstrippling89@ow.ly', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Peri', 'Szantho', null, '41-828-0304', 'pbrixey8a@nba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Clari', 'Veneur', null, '72-821-3530', 'ctrineman8b@friendfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Ashien', 'Greedier', 'Treadwell', '12-284-9986', 'atreadwell8c@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Ibrahim', 'Jouhan', 'Outridge', '28-458-9404', 'ioutridge8d@gravatar.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Olwen', 'Albasiny', 'Spurdle', '96-332-4122', 'ospurdle8e@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Murry', 'Hanrahan', 'Bladen', '79-901-0731', 'mbladen8f@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Cori', 'Digle', 'Swaite', '92-975-3486', 'cswaite8g@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Glen', 'Leak', 'Copeman', '90-039-5687', 'gcopeman8h@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Beret', 'Wrankling', 'Giacobazzi', '57-861-0389', 'bgiacobazzi8i@yellowbook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Mill', 'Ghiron', 'Hicks', '86-938-0978', 'mhicks8j@hubpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Mario', 'Roland', 'Adame', '32-884-2806', 'madame8k@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Cristy', 'Shetliff', 'Simon', '50-100-7856', 'csimon8l@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Dugald', 'Critten', 'Polglaze', '43-091-6580', 'dpolglaze8m@yandex.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Allx', 'Le Marchand', null, '33-727-0238', 'adanser8n@squarespace.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Gates', 'Maddaford', 'Ridolfi', '66-412-7178', 'gridolfi8o@bbc.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Desmond', 'De Bischop', 'Rintoul', '67-124-0253', 'drintoul8p@cyberchimps.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Oona', 'Febre', 'Redihough', '42-486-6770', 'oredihough8q@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Craggie', 'Sharratt', null, '78-677-7180', 'csmithen8r@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Lucinda', 'Coate', 'Beneze', '30-628-7373', 'lbeneze8s@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Vladimir', 'Prosek', 'Kennagh', '83-441-4390', 'vkennagh8t@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Kennett', 'Fairall', 'Heavyside', '97-907-5221', 'kheavyside8u@ezinearticles.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Jarrett', 'Jiggen', 'Beecraft', '18-539-4371', 'jbeecraft8v@uol.com.br', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Verina', 'Peck', 'Hethron', '08-072-3979', 'vhethron8w@ezinearticles.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Meggy', 'Downer', null, '96-852-6369', 'mcoom8x@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Vail', 'Arch', 'Elsmor', '09-378-4412', 'velsmor8y@slashdot.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Thia', 'Loughran', 'Gresser', '46-067-9552', 'tgresser8z@devhub.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Der', 'Benfield', null, '10-897-6721', 'dtysall90@weather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Lu', 'Beaver', 'Headon', '71-242-3720', 'lheadon91@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Crista', 'O''Flynn', 'Guiett', '13-959-3582', 'cguiett92@intel.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Rozanne', 'Frarey', 'Neylan', '19-661-5590', 'rneylan93@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Zia', 'Coathup', 'Green', '07-378-1752', 'zgreen94@nationalgeographic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Aubrette', 'Kynforth', 'Ouslem', '43-507-0831', 'aouslem95@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Reuben', 'Trebilcock', 'Huban', '62-490-4098', 'rhuban96@noaa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Theodosia', 'Manuaud', 'Massow', '39-451-8040', 'tmassow97@joomla.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Dorris', 'Ilyasov', 'Bysaker', '54-291-2196', 'dbysaker98@i2i.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Kennith', 'Calcott', 'Curton', '87-022-7382', 'kcurton99@printfriendly.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Erinna', 'MacEntee', 'Juster', '38-751-2115', 'ejuster9a@reverbnation.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Griffie', 'Piborn', 'Hudghton', '49-538-6890', 'ghudghton9b@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Lorette', 'Mico', 'McCahill', '85-442-7956', 'lmccahill9c@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Brina', 'Wetheril', 'Kennerknecht', '81-656-6507', 'bkennerknecht9d@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Karney', 'Beyn', 'Dedenham', '05-631-7524', 'kdedenham9e@statcounter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Joycelin', 'Whiteman', 'Klug', '73-787-5033', 'jklug9f@yolasite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Merci', 'Greenman', 'Brummitt', '62-774-7858', 'mbrummitt9g@accuweather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Andy', 'Shrawley', 'Mashro', '62-156-2694', 'amashro9h@pen.io', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Dela', 'Friary', 'Vatcher', '39-579-6428', 'dvatcher9i@wunderground.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Jenine', 'Larkby', 'Clinkard', '93-899-7007', 'jclinkard9j@oracle.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Rosanna', 'Bradane', 'Spruce', '96-710-2943', 'rspruce9k@deviantart.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Kattie', 'Jarrold', 'Grassett', '97-891-7776', 'kgrassett9l@youtube.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Zachery', 'Limbrick', 'Wrankmore', '12-555-5772', 'zwrankmore9m@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Merle', 'Bowstead', 'Nabarro', '21-765-8996', 'mnabarro9n@artisteer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Gregorius', 'Corkish', 'Le Prevost', '86-475-0535', 'gleprevost9o@imageshack.us', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Dudley', 'Matyushenko', 'Loveless', '15-069-2665', 'dloveless9p@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Janka', 'Vasyunin', 'Choldcroft', '93-268-9958', 'jcholdcroft9q@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Dave', 'Doni', 'Heselwood', '90-979-6065', 'dheselwood9r@fema.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Halsy', 'Shulver', 'Scoyne', '22-384-5220', 'hscoyne9s@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Ingar', 'Daubeny', 'Seres', '62-415-0979', 'iseres9t@dmoz.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Lura', 'Langrish', 'Sedgeman', '39-313-8167', 'lsedgeman9u@aol.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Ynez', 'Landell', null, '57-441-0904', 'yconkey9v@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Charlie', 'Goede', null, '17-740-7048', 'cvicar9w@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Ethelda', 'Willcot', 'Rizzardi', '49-002-3149', 'erizzardi9x@friendfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Redford', 'Stollen', null, '04-341-5993', 'rmacsween9y@businesswire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Rafaellle', 'Deverock', 'Poytres', '18-750-4930', 'rpoytres9z@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Kev', 'Matuszewski', null, '95-862-8131', 'kwilcockesa0@japanpost.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Crysta', 'deKnevet', 'Burehill', '22-436-4713', 'cburehilla1@usnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Julie', 'Fosdike', 'Batrim', '59-066-7143', 'jbatrima2@omniture.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Jaime', 'Setterfield', 'Joscelyn', '13-786-5819', 'jjoscelyna3@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Hedda', 'Lawlan', 'Bracco', '27-063-0311', 'hbraccoa4@gov.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Ezechiel', 'Haliday', 'Mazonowicz', '17-361-0016', 'emazonowicza5@vinaora.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Tawsha', 'Torrance', 'Aliman', '31-472-2293', 'talimana6@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Saxe', 'Brokenshire', 'Lacroutz', '03-817-5888', 'slacroutza7@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Justus', 'Edwinson', 'Darwin', '97-631-8513', 'jdarwina8@deliciousdays.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Maurizio', 'Wantling', 'Goulden', '90-357-6548', 'mgouldena9@shutterfly.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Ariadne', 'Linde', 'Burvill', '74-865-6861', 'aburvillaa@weebly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Weidar', 'Tearle', 'Bilam', '62-164-8541', 'wbilamab@craigslist.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Waldo', 'Dainton', 'Ockleshaw', '16-069-3994', 'wockleshawac@liveinternet.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Raynor', 'Gwillyam', 'Abbati', '52-546-0398', 'rabbatiad@redcross.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Aurelie', 'Rudge', 'Estcourt', '50-336-9605', 'aestcourtae@ezinearticles.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'Elfrieda', 'Starford', 'Knowlman', '67-224-9181', 'eknowlmanaf@mit.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Selia', 'Cullabine', 'Dewire', '51-270-0464', 'sdewireag@amazon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Coriss', 'Nuzzi', 'Glavis', '86-868-9774', 'cglavisah@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Giustino', 'Burland', 'Turri', '39-475-5755', 'gturriai@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Harald', 'Lesser', 'Gofton', '40-991-3587', 'hgoftonaj@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Stephana', 'Niece', 'Dresse', '16-460-4760', 'sdresseak@forbes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Millisent', 'Skym', 'Braz', '56-999-6865', 'mbrazal@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Bartholemy', 'Beat', 'Afonso', '53-231-1588', 'bafonsoam@accuweather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Martino', 'Bramwell', 'Harroll', '22-665-5938', 'mharrollan@cocolog-nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Taffy', 'Kitchen', 'Pinney', '76-236-4627', 'tpinneyao@joomla.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Ermanno', 'Spittall', 'Bezarra', '21-039-5944', 'ebezarraap@biglobe.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'Artemis', 'Bausor', 'Van Brug', '97-817-5357', 'avanbrugaq@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Carin', 'Wooding', null, '22-655-1683', 'chitzschkear@vinaora.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Fey', 'Bottelstone', null, '72-563-0697', 'fsandsallanas@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Reggy', 'Ahlf', 'Lamshead', '16-791-4066', 'rlamsheadat@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Row', 'Loxston', 'McGiveen', '70-097-4920', 'rmcgiveenau@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Marena', 'Haycox', 'Loudwell', '08-842-7460', 'mloudwellav@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Aaron', 'Pennicott', 'Billett', '66-474-7776', 'abillettaw@answers.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Liza', 'Szepe', 'Duferie', '38-882-7364', 'lduferieax@unesco.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Pryce', 'Baythrop', null, '70-162-7619', 'pcarpenteray@indiatimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Rosabelle', 'Oaten', 'Mewhirter', '02-036-1838', 'rmewhirteraz@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Regan', 'Cholomin', 'Spurden', '40-510-0365', 'rspurdenb0@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Bret', 'Trenholm', 'Chedgey', '09-862-0976', 'bchedgeyb1@zdnet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Dukey', 'D''eath', 'Thurston', '06-565-0495', 'dthurstonb2@goodreads.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Kelbee', 'Blare', 'Charlet', '55-666-9659', 'kcharletb3@ebay.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Barthel', 'Corey', 'Leving', '47-709-3861', 'blevingb4@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Jennie', 'Beldam', 'Whittam', '97-033-5898', 'jwhittamb5@mtv.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Ingemar', 'Bilovus', 'Girk', '48-469-1724', 'igirkb6@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Marcellus', 'Capponer', 'Showt', '28-156-5304', 'mshowtb7@nature.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Saleem', 'O''Mannion', 'Bruhke', '65-755-9238', 'sbruhkeb8@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Sheelah', 'Whittington', null, '23-498-8299', 'spalatinib9@cisco.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Diana', 'Wethers', 'Fatharly', '01-119-6340', 'dfatharlyba@usgs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Vannie', 'Nutley', null, '00-577-9983', 'vbacklerbb@soundcloud.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Kane', 'Carlisso', 'Thomesson', '63-499-4369', 'kthomessonbc@hugedomains.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Demetre', 'Maggiore', 'Rawling', '64-069-5893', 'drawlingbd@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Donnell', 'Medlar', 'Dunnett', '56-556-5180', 'ddunnettbe@nifty.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Sallyanne', 'Luca', 'Mohring', '64-555-5761', 'smohringbf@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Nial', 'Wooles', 'Grouen', '93-622-4777', 'ngrouenbg@psu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Faythe', 'Mahaddie', null, '41-021-7539', 'fmurrhauptbh@ezinearticles.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Dianna', 'MacCafferty', 'Leith-Harvey', '44-559-5986', 'dleithharveybi@bloomberg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Nonie', 'Mackness', null, '53-557-4397', 'ndunbobbinbj@xing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Petronilla', 'Orro', 'Rosenkrantz', '11-076-5536', 'prosenkrantzbk@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Susette', 'O''Sharkey', 'Erdis', '77-009-8077', 'serdisbl@chronoengine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Sigrid', 'Lawry', 'Wedderburn', '51-126-7344', 'swedderburnbm@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Dexter', 'Stiller', 'Brands', '47-034-4190', 'dbrandsbn@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Cordi', 'Woolatt', 'Antrobus', '64-923-9461', 'cantrobusbo@apache.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Gaylor', 'Grzelczak', 'Marquess', '29-068-2773', 'gmarquessbp@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Broddie', 'Tremmel', 'Heiton', '03-990-0349', 'bheitonbq@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Martainn', 'Molloy', 'Freake', '09-727-2495', 'mfreakebr@irs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Dannye', 'Shambrooke', 'Kingerby', '38-582-7742', 'dkingerbybs@springer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Inger', 'Van Zon', 'Virgin', '02-095-2574', 'ivirginbt@washington.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Hetti', 'Gueny', 'Cubbinelli', '04-415-6785', 'hcubbinellibu@people.com.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Phedra', 'Cannaway', 'Keeting', '56-236-5878', 'pkeetingbv@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Emmalynn', 'Rubery', 'Crosetti', '04-984-7619', 'ecrosettibw@sogou.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Patricio', 'Dziwisz', 'Varne', '17-111-6841', 'pvarnebx@unc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Viviana', 'McMains', 'Hawke', '75-712-5838', 'vhawkeby@1und1.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Augusta', 'Ivanchikov', 'Fenck', '69-316-9822', 'afenckbz@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Lari', 'Tettersell', 'Powling', '27-231-2669', 'lpowlingc0@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Roley', 'Le Barre', 'Schoular', '76-573-4346', 'rschoularc1@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Zorana', 'Crebott', 'Moyers', '87-107-6313', 'zmoyersc2@earthlink.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Tiphani', 'Heyworth', 'Keattch', '40-994-8681', 'tkeattchc3@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Aggy', 'Marder', 'Luesley', '40-465-6063', 'aluesleyc4@npr.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Casandra', 'Greenstreet', 'Huntingford', '85-778-6020', 'chuntingfordc5@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Connie', 'Foch', 'Toma', '41-577-9064', 'ctomac6@independent.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Edvard', 'Roofe', null, '17-965-1222', 'enemchinovc7@ted.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Odelle', 'Kaplin', 'Bewsey', '06-113-8787', 'obewseyc8@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Bruis', 'Brok', 'Lauchlan', '05-685-6381', 'blauchlanc9@rambler.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Mikael', 'Crutch', 'Kuzemka', '58-426-8491', 'mkuzemkaca@blogspot.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Hanny', 'Giacometti', 'Naisbitt', '91-098-8892', 'hnaisbittcb@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Vladamir', 'Allone', 'Mattia', '90-049-3245', 'vmattiacc@zimbio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Emmott', 'Quixley', 'Churm', '26-985-7095', 'echurmcd@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Tanhya', 'Bunyan', 'Jersch', '31-013-8127', 'tjerschce@boston.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Quentin', 'Desbrow', 'Sandiford', '38-420-5478', 'qsandifordcf@noaa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Aloisia', 'Birkenhead', null, '19-212-0336', 'aivakhnocg@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Rubin', 'Poller', 'Offa', '97-720-6038', 'roffach@miitbeian.gov.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Otis', 'Alison', 'Winslow', '55-422-0407', 'owinslowci@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Roseann', 'Colcutt', 'Staley', '58-297-7785', 'rstaleycj@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Trip', 'Devenish', 'Meffan', '98-572-7163', 'tmeffanck@issuu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Anya', 'Simonnin', null, '91-948-3921', 'aadkincl@independent.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Helaine', 'Burley', 'Benck', '56-849-8513', 'hbenckcm@4shared.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Chere', 'Ryburn', null, '08-835-8508', 'ckeddiecn@whitehouse.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Rafaelia', 'Sawfoot', 'Goldster', '62-034-6931', 'rgoldsterco@canalblog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Wilt', 'O'' Culligan', 'Buey', '87-194-9594', 'wbueycp@yelp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Ethel', 'Stinson', 'Cubin', '62-048-2896', 'ecubincq@opera.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Val', 'Brunger', null, '32-774-9692', 'vjoycecr@webeden.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Jose', 'Bitten', 'Haslen', '41-747-6837', 'jhaslencs@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Lenee', 'Love', 'Gentner', '38-923-5382', 'lgentnerct@eventbrite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Olly', 'Romanet', 'Leming', '43-406-5351', 'olemingcu@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Kean', 'Dran', 'Padley', '97-197-0638', 'kpadleycv@army.mil', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Charmine', 'Kumaar', 'Charlewood', '61-168-3907', 'ccharlewoodcw@t.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Natasha', 'Epinoy', null, '63-502-6514', 'nnergercx@java.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Jarred', 'Tills', 'Haddrill', '21-941-7269', 'jhaddrillcy@cam.ac.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Diarmid', 'Scottesmoor', 'Donohoe', '28-165-8882', 'ddonohoecz@de.vu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Anastasie', 'Marini', 'Lyne', '47-681-2011', 'alyned0@fda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Jobey', 'Bedome', 'Nunson', '73-192-4898', 'jnunsond1@google.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Vivianne', 'Ambrogetti', null, '13-542-7938', 'vkenningleyd2@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Hobey', 'Ebbles', 'Bothram', '88-556-4174', 'hbothramd3@whitehouse.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Sharia', 'Sewall', null, '21-521-6980', 'sduckworthd4@apache.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Wilie', 'Ewenson', 'Morphet', '02-023-5284', 'wmorphetd5@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Kirk', 'Shand', 'Sellner', '55-992-5629', 'ksellnerd6@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Justus', 'Danilovich', null, '98-031-8940', 'jburdekind7@google.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Margalo', 'Pouck', 'Roubottom', '13-092-6932', 'mroubottomd8@gov.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Teirtza', 'Mothersole', 'Cornelissen', '34-092-7640', 'tcornelissend9@vistaprint.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Verena', 'Klicher', 'Lineker', '68-829-0619', 'vlinekerda@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Janka', 'Kruse', 'Andri', '61-371-1539', 'jandridb@wisc.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Jarred', 'McGebenay', 'Bassett', '92-253-9677', 'jbassettdc@4shared.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Jacky', 'Scouse', 'Elsie', '96-378-4124', 'jelsiedd@mapy.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Marigold', 'Pohling', 'Linton', '52-580-3269', 'mlintonde@mozilla.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Jorry', 'Hartle', 'Eldredge', '54-390-8115', 'jeldredgedf@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Juliana', 'Taggerty', null, '42-963-6384', 'jfurphydg@goo.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Kattie', 'Daid', 'Lorenzo', '94-772-6355', 'klorenzodh@prlog.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Hanna', 'Whitwham', 'Lanahan', '70-062-4176', 'hlanahandi@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Grete', 'Renon', 'Chavez', '43-759-7420', 'gchavezdj@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Vittoria', 'Goodale', 'Sherrington', '72-991-3094', 'vsherringtondk@gov.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Mendy', 'Castles', 'Ort', '08-647-3119', 'mortdl@nature.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Gwenni', 'Dudderidge', 'Grigson', '34-213-2250', 'ggrigsondm@harvard.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Modesta', 'Verden', 'Kilroy', '17-248-2721', 'mkilroydn@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Rosaline', 'Stapley', null, '74-078-8686', 'rtaylotdo@slate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Josiah', 'Rubica', 'McMakin', '80-098-7734', 'jmcmakindp@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Garvin', 'McSperrin', 'Pourvoieur', '21-338-7778', 'gpourvoieurdq@furl.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Aldous', 'Knightly', 'Roxburgh', '33-725-9386', 'aroxburghdr@mashable.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Jody', 'Salvadore', 'Meharry', '16-806-8687', 'jmeharryds@wikimedia.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Bev', 'Bauer', 'Dyett', '78-185-8386', 'bdyettdt@usgs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Martainn', 'Narramor', 'Ludron', '65-548-1926', 'mludrondu@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Lorenza', 'Poundesford', 'Styant', '73-369-1408', 'lstyantdv@quantcast.com', null);
