insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Benyamin', 'Jewis', 'Fransemai', '49-724-8397', 'bfransemai0@timesonline.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Avis', 'Pepye', 'Gantzman', '91-976-3539', 'agantzman1@xing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Gabie', 'Varlow', null, '81-614-7401', 'glendon2@google.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Raquela', 'Palk', 'Amps', '30-982-0598', 'ramps3@odnoklassniki.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Othilia', 'Giveen', 'Scatcher', '79-248-5625', 'oscatcher4@pbs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Wini', 'Cruickshank', null, '13-440-3151', 'wtansly5@people.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Lavena', 'Romayn', 'Balbeck', '28-514-1539', 'lbalbeck6@upenn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Kylie', 'Mulhall', 'Danzey', '60-668-1174', 'kdanzey7@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Robinetta', 'Doughartie', 'Marlen', '76-871-7451', 'rmarlen8@biglobe.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Reinald', 'Vittery', null, '29-150-1878', 'rfishwick9@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Berrie', 'Preston', 'Gunning', '84-010-6225', 'bgunninga@woothemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Arte', 'Brophy', null, '02-746-7265', 'abohanb@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Reuben', 'Giacovelli', null, '67-142-6152', 'rlockec@livejournal.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Dniren', 'Proback', 'Apperley', '41-326-8377', 'dapperleyd@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Babette', 'Casewell', 'Mackerel', '02-942-3951', 'bmackerele@yahoo.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Linnet', 'Pardon', 'Colnett', '08-976-7658', 'lcolnettf@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Luz', 'Hooban', 'Eckh', '93-777-2766', 'leckhg@illinois.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Janela', 'Flaubert', 'Daynter', '67-850-5019', 'jdaynterh@gnu.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Mirabel', 'Swinbourne', null, '07-763-3407', 'medghinni@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Esra', 'MacAleese', 'Melburg', '25-166-0158', 'emelburgj@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Stanley', 'Jakucewicz', 'Ranyell', '06-801-2292', 'sranyellk@fema.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Early', 'Meindl', 'Goodhall', '60-266-8734', 'egoodhalll@hostgator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Ronnie', 'Pulhoster', 'Hatz', '17-213-5271', 'rhatzm@slashdot.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Elfie', 'Arnholdt', 'Philo', '35-084-9471', 'ephilon@i2i.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Birk', 'Rainbird', null, '84-480-4759', 'bkarrano@about.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Marline', 'Tinsley', 'Legier', '50-020-6207', 'mlegierp@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Ariela', 'Puttick', 'Feakins', '78-729-4008', 'afeakinsq@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Daveta', 'Makeswell', 'Cubitt', '31-343-4045', 'dcubittr@si.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Patsy', 'Sayle', 'Marnane', '26-814-8984', 'pmarnanes@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Annadiane', 'Hurdis', null, '25-521-9329', 'ahonscht@delicious.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Delinda', 'Andreopolos', 'MacKeague', '95-467-6052', 'dmackeagueu@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Mycah', 'O''Scanlon', 'Brodeau', '17-912-1588', 'mbrodeauv@cyberchimps.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'Joyann', 'Mustill', 'Sheard', '74-780-0931', 'jsheardw@meetup.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Andres', 'Kitching', 'Smith', '14-733-2937', 'asmithx@timesonline.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Desmund', 'Quincee', null, '56-528-8130', 'dswetmorey@sohu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Vivien', 'Staff', 'Gilding', '13-673-0063', 'vgildingz@sbwire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Dorothy', 'Tudgay', 'Luberto', '48-606-5796', 'dluberto10@google.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Agata', 'Branton', 'Vinas', '48-041-0248', 'avinas11@army.mil', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Jethro', 'Rhubottom', 'Deane', '21-735-8427', 'jdeane12@plala.or.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Heall', 'Le Galle', 'Cuttle', '15-251-6458', 'hcuttle13@rediff.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Genevieve', 'Pavlov', 'Lamble', '11-716-2895', 'glamble14@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Alice', 'Cave', 'Lundie', '53-112-8924', 'alundie15@facebook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Celestyn', 'Petrosian', 'Gailor', '55-304-0417', 'cgailor16@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Carlie', 'Vase', null, '57-724-6381', 'cclubbe17@google.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Romonda', 'Kitteridge', 'Alloisi', '92-948-7954', 'ralloisi18@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Langsdon', 'Lamborne', 'McBrearty', '15-744-9617', 'lmcbrearty19@xrea.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Peyter', 'Badrock', 'Howse', '77-080-7901', 'phowse1a@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'Noelle', 'Leavy', 'Harradence', '08-469-1398', 'nharradence1b@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Herculie', 'Spellacey', 'Keys', '57-367-0927', 'hkeys1c@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Lucine', 'Ebunoluwa', 'Nutley', '46-359-9638', 'lnutley1d@opensource.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Madelene', 'Schwaiger', 'Prester', '63-609-6417', 'mprester1e@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Riki', 'Jessett', 'Dury', '82-506-8362', 'rdury1f@vimeo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Hattie', 'Dinsmore', 'Duffrie', '14-457-8212', 'hduffrie1g@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Romola', 'Muccino', 'Murdie', '28-658-1677', 'rmurdie1h@creativecommons.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Stavros', 'Grills', 'Coaster', '45-699-6889', 'scoaster1i@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Rodrigo', 'Ealam', 'Guiet', '90-376-0990', 'rguiet1j@apache.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Andi', 'Lippett', 'Sopp', '65-080-7515', 'asopp1k@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Broddie', 'Pipe', null, '76-933-7099', 'bstormes1l@biglobe.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Pebrook', 'Matzl', null, '37-897-4697', 'pbromidge1m@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Torre', 'Siddele', null, '24-863-4442', 'tdodsworth1n@last.fm', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Kylie', 'Fieldsend', 'Arrigucci', '19-357-5178', 'karrigucci1o@yolasite.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Dona', 'Hadgkiss', 'Nellies', '09-735-6930', 'dnellies1p@1688.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Nessie', 'Sunner', 'Aldham', '50-977-0366', 'naldham1q@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Teodoro', 'Brownbill', 'Olexa', '55-751-8207', 'tolexa1r@wsj.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Lindsy', 'Gonsalvo', 'Yerborn', '79-988-6873', 'lyerborn1s@sitemeter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Pooh', 'Ledner', 'Doole', '49-398-9252', 'pdoole1t@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Leonie', 'Scuse', 'Thickett', '97-029-9020', 'lthickett1u@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Vale', 'Smythin', null, '26-416-5420', 'vhulcoop1v@youtu.be', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Petr', 'Markos', null, '58-082-4566', 'pcess1w@jugem.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Orion', 'Jirik', 'Ballham', '59-770-4694', 'oballham1x@amazon.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Humberto', 'Tolle', 'Lappin', '35-624-4233', 'hlappin1y@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Sheffy', 'Clowser', 'Denness', '46-323-6035', 'sdenness1z@technorati.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Rois', 'Skeech', 'Jelleman', '82-059-3696', 'rjelleman20@tumblr.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Cristine', 'Wakely', 'Blenkharn', '68-052-9086', 'cblenkharn21@opensource.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Ellene', 'Bolens', 'Sutheran', '53-867-3543', 'esutheran22@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Charissa', 'Borer', 'Guittet', '09-676-6544', 'cguittet23@geocities.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Helen-elizabeth', 'Conrath', 'Kenward', '29-784-1350', 'hkenward24@answers.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Haywood', 'Iacopetti', 'Denson', '54-362-0581', 'hdenson25@tmall.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Ernst', 'Partington', 'Krout', '09-118-3305', 'ekrout26@microsoft.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Isiahi', 'Ackland', 'Maundrell', '91-820-1047', 'imaundrell27@archive.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Jobie', 'Rosen', 'Padson', '95-891-7120', 'jpadson28@washingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Rosanne', 'Hansed', 'Rosini', '17-101-3994', 'rrosini29@businesswire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Jojo', 'Tenniswood', 'Solland', '08-449-2579', 'jsolland2a@tripod.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Northrop', 'Cromie', 'Peacher', '96-251-2268', 'npeacher2b@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Donny', 'Tomsa', null, '23-770-9559', 'dduer2c@bbc.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Daffy', 'Beastall', 'Fernehough', '73-917-9100', 'dfernehough2d@amazon.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Wilona', 'Ege', 'Rousby', '56-966-9474', 'wrousby2e@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Lucy', 'MacTerrelly', 'Iannetti', '51-649-2344', 'liannetti2f@miibeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Roi', 'Chevins', 'Upston', '46-052-5508', 'rupston2g@sciencedirect.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Cord', 'Burbridge', null, '04-237-4998', 'ccurwood2h@sbwire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Sandor', 'McGibbon', null, '19-456-2275', 'sbeslier2i@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Sigrid', 'Dankov', 'Walentynowicz', '33-865-9526', 'swalentynowicz2j@virginia.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Tildi', 'Jakobsson', 'Neeves', '40-982-4465', 'tneeves2k@marriott.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Baron', 'Dorr', null, '84-507-2171', 'blongthorne2l@homestead.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Adella', 'Sarton', 'Sivill', '93-168-9349', 'asivill2m@goodreads.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Chaddy', 'MacCourt', 'Doblin', '88-119-9945', 'cdoblin2n@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Gerladina', 'Tomblett', 'Trevna', '32-213-7548', 'gtrevna2o@hao123.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Rochella', 'Broyd', null, '13-119-4520', 'rgrinham2p@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Hymie', 'Bonevant', 'Wyldbore', '21-133-6806', 'hwyldbore2q@zimbio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Vilma', 'Franks', 'Sallter', '00-341-0982', 'vsallter2r@marketwatch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Sarita', 'Bulman', 'Spaxman', '92-396-2419', 'sspaxman2s@nymag.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Pate', 'Edinboro', 'Houlaghan', '91-929-8781', 'phoulaghan2t@wsj.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Eva', 'Shildrake', 'Charlin', '69-581-3654', 'echarlin2u@fc2.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Mauricio', 'Chart', 'Schwaiger', '91-811-1008', 'mschwaiger2v@weibo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Hailey', 'Pauler', null, '09-773-1805', 'hlardeux2w@youtube.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Dominick', 'Cornall', null, '27-051-1760', 'dbarnewelle2x@slashdot.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Valene', 'Gomez', 'Pilmer', '44-840-6728', 'vpilmer2y@craigslist.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Fiorenze', 'Drennan', 'McReedy', '67-030-9806', 'fmcreedy2z@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Glendon', 'Berntssen', null, '81-318-9493', 'gvickery30@posterous.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Perry', 'Arens', 'Gilman', '64-363-7159', 'pgilman31@istockphoto.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Dino', 'Fitzsymons', 'Whitebread', '91-608-8853', 'dwhitebread32@phpbb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Beck', 'Calvey', 'Mattecot', '84-988-6451', 'bmattecot33@dropbox.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Arch', 'Bartolommeo', 'Swedeland', '90-844-2294', 'aswedeland34@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Lorne', 'Ginity', 'Holburn', '08-265-3659', 'lholburn35@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Ludwig', 'Tarrant', null, '02-042-8049', 'lgermon36@berkeley.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Andrei', 'Huxham', 'Fibben', '35-186-3480', 'afibben37@twitpic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Sheffield', 'Fayter', 'Sach', '09-670-4658', 'ssach38@zdnet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Dasha', 'Hovie', 'Longo', '05-705-4924', 'dlongo39@squarespace.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Donaugh', 'Noble', 'Lapidus', '87-982-2793', 'dlapidus3a@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Fidelity', 'Anand', null, '99-717-6302', 'fveque3b@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Cristie', 'Andrin', 'Londors', '30-287-3759', 'clondors3c@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Nada', 'Barends', 'Hinder', '45-390-3075', 'nhinder3d@myspace.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Lucienne', 'Whistan', 'Tear', '80-915-0341', 'ltear3e@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Kaylyn', 'Sexten', 'Brockherst', '33-118-7374', 'kbrockherst3f@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Piggy', 'Scotchmor', 'Farmiloe', '46-405-2783', 'pfarmiloe3g@youtu.be', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Cyndy', 'Bellino', 'Deppen', '60-181-1439', 'cdeppen3h@hc360.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Gerome', 'Bampforth', 'Keets', '69-335-8821', 'gkeets3i@cnbc.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Gerhard', 'Wisniewski', 'Wannop', '76-290-9744', 'gwannop3j@1und1.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Terri', 'Wormleighton', null, '21-466-3139', 'tlegan3k@columbia.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Nate', 'Munby', 'Morrish', '14-688-2419', 'nmorrish3l@gmpg.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Catlin', 'Kitteringham', null, '79-214-4446', 'cseiffert3m@ebay.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Virgie', 'Olley', 'Benettelli', '18-889-4892', 'vbenettelli3n@adobe.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Alexi', 'Salters', 'Porch', '53-054-1118', 'aporch3o@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Cher', 'Sorensen', 'Soppett', '47-651-6170', 'csoppett3p@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Kerry', 'Storror', 'Arrighi', '72-552-6606', 'karrighi3q@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Bonnibelle', 'Whittlesey', 'Tevelov', '30-198-8775', 'btevelov3r@hc360.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Burnaby', 'Kellogg', 'Simchenko', '13-847-5904', 'bsimchenko3s@sbwire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Charley', 'Moffett', 'Gowing', '52-448-3295', 'cgowing3t@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Emmalynne', 'Snaith', 'Normaville', '32-017-4004', 'enormaville3u@marriott.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Ofella', 'Ostrich', null, '94-274-4958', 'opennycuick3v@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Valentino', 'Rosenbarg', 'Missen', '74-090-9118', 'vmissen3w@dagondesign.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Lamont', 'Balint', 'Beall', '55-080-3134', 'lbeall3x@t.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Forster', 'Bayless', 'Wilkowski', '21-634-2591', 'fwilkowski3y@canalblog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Reginauld', 'Longthorn', 'Parkyns', '45-352-2926', 'rparkyns3z@pagesperso-orange.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Cele', 'Hadcroft', 'Paterno', '14-067-9209', 'cpaterno40@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Mervin', 'Giorgietto', 'Reubbens', '40-533-9629', 'mreubbens41@github.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Eberto', 'Dealy', 'Whyberd', '79-641-5992', 'ewhyberd42@people.com.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Belicia', 'Leehane', 'Dinsmore', '36-339-0532', 'bdinsmore43@latimes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Susie', 'Caudrelier', 'Seden', '58-089-5641', 'sseden44@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Sabine', 'Bawden', 'Mainston', '17-178-3800', 'smainston45@networkadvertising.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Orson', 'Addis', 'Hessle', '06-729-9805', 'ohessle46@icio.us', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Worthington', 'Tummons', 'Stickells', '44-698-7862', 'wstickells47@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Filbert', 'Ashton', 'Benam', '97-966-4091', 'fbenam48@ca.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Kristos', 'McGettigan', 'Barthel', '56-176-0140', 'kbarthel49@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Judah', 'Chapman', null, '64-200-4720', 'jcharsley4a@cyberchimps.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Revkah', 'Dominiak', 'Loughren', '69-432-0232', 'rloughren4b@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Artur', 'Figgins', 'Rissen', '89-873-9160', 'arissen4c@dedecms.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Luella', 'Kerr', null, '02-987-1973', 'lgatty4d@gizmodo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Lawton', 'Malinson', 'Chaldecott', '22-162-2029', 'lchaldecott4e@slate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Kath', 'Oneile', 'Kubyszek', '06-618-2425', 'kkubyszek4f@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Bettye', 'Gasnell', 'Rumbellow', '28-245-5322', 'brumbellow4g@miibeian.gov.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Philly', 'Jefferys', 'Yesinov', '96-440-1943', 'pyesinov4h@epa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Kiley', 'Dimitriou', 'Hacon', '08-000-9393', 'khacon4i@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Gunter', 'Blackden', 'Madden', '76-312-5442', 'gmadden4j@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Veriee', 'Lambricht', 'Tillot', '85-845-6134', 'vtillot4k@spotify.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Mahala', 'Hankard', null, '08-838-7842', 'mboow4l@accuweather.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Ruthe', 'Brophy', null, '47-788-4540', 'rgrayham4m@telegraph.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Carole', 'Sheach', null, '13-084-0986', 'cgonthier4n@ask.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Albrecht', 'Batie', 'Greeves', '08-437-3033', 'agreeves4o@cloudflare.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Ivan', 'Henmarsh', 'Currer', '06-670-9396', 'icurrer4p@unesco.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Burk', 'Stuchbury', 'Manon', '51-523-3165', 'bmanon4q@spotify.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Josiah', 'Desesquelle', 'Penton', '07-050-5712', 'jpenton4r@nasa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Kimberly', 'Foxwell', 'McNeilley', '45-813-4624', 'kmcneilley4s@businesswire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Laird', 'Bromige', 'Middle', '77-991-5816', 'lmiddle4t@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Etti', 'Boldecke', null, '43-564-1844', 'efloat4u@springer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Webster', 'McElroy', 'Ickovitz', '70-698-3218', 'wickovitz4v@chron.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Anatollo', 'Helgass', 'Works', '88-426-5626', 'aworks4w@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Davin', 'Redwing', 'Roll', '49-695-4275', 'droll4x@guardian.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Leeann', 'Paulino', null, '66-534-8207', 'llehrer4y@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Jarrid', 'Moulds', 'Thoday', '88-046-3688', 'jthoday4z@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Dulcie', 'Fayerman', null, '63-457-0432', 'dshearsby50@wordpress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Rory', 'Argente', null, '55-210-6636', 'rdany51@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Bertie', 'Pybworth', 'Leupoldt', '50-111-2370', 'bleupoldt52@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Leontyne', 'Camerello', 'Muncaster', '79-403-6083', 'lmuncaster53@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Nita', 'Kattenhorn', null, '38-880-6251', 'nhirthe54@bravesites.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Tybi', 'Chartre', 'Flear', '45-219-7634', 'tflear55@guardian.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Ham', 'Aitchinson', 'Spellard', '06-889-4028', 'hspellard56@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Latrena', 'Ladel', 'Ault', '16-038-0281', 'lault57@cornell.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Jeramie', 'Weaving', 'Wisdish', '87-804-7481', 'jwisdish58@mtv.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Xavier', 'O''Lagen', 'Pessold', '27-292-5822', 'xpessold59@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Layla', 'Kinkade', 'Benz', '70-148-0687', 'lbenz5a@moonfruit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Stu', 'Isenor', null, '95-392-9423', 'sbotly5b@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Warner', 'Gerge', 'Gurnee', '63-799-4953', 'wgurnee5c@nyu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Dian', 'Sellens', 'Twittey', '87-391-3542', 'dtwittey5d@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Dominga', 'Southernwood', 'Weatherall', '54-022-4175', 'dweatherall5e@i2i.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Robbie', 'Critchard', null, '89-363-4398', 'ride5f@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Heriberto', 'Geyton', 'Godthaab', '03-514-4190', 'hgodthaab5g@google.nl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Kiley', 'Ucchino', 'Leguay', '28-641-9279', 'kleguay5h@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Fowler', 'McElhinney', 'Slator', '43-572-5616', 'fslator5i@ovh.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Gustie', 'Cressor', 'Lakenton', '92-177-0691', 'glakenton5j@marketwatch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Kassandra', 'Stanex', 'Ceschi', '84-394-5254', 'kceschi5k@quantcast.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Roselle', 'Bea', 'Cazalet', '97-235-6366', 'rcazalet5l@sciencedaily.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Giorgia', 'Ragsdale', null, '34-899-6792', 'gblemen5m@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Wendeline', 'Crees', 'Wann', '04-058-1467', 'wwann5n@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Brinna', 'Simonassi', null, '78-541-4247', 'bsottell5o@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Catherine', 'Axworthy', 'Ellif', '69-091-1528', 'cellif5p@latimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Glad', 'Adshad', 'Dinning', '29-670-0528', 'gdinning5q@opera.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Blair', 'Gimbrett', 'McCrillis', '05-751-9459', 'bmccrillis5r@hao123.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Roddie', 'Magnus', null, '16-787-8478', 'rpenwright5s@fc2.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Hakim', 'Richarson', 'Sails', '92-397-8610', 'hsails5t@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Wyn', 'Barthrup', 'Beeze', '89-962-5935', 'wbeeze5u@taobao.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Christabel', 'Gounet', 'Preddle', '96-612-0131', 'cpreddle5v@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Cameron', 'Gair', 'Longdon', '70-494-2188', 'clongdon5w@eventbrite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Gavin', 'Mordecai', 'Hassan', '77-474-9946', 'ghassan5x@irs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'Brier', 'O'' Flaherty', null, '89-214-0383', 'bsavory5y@gov.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Shandie', 'Fidge', null, '70-937-3829', 'sstidworthy5z@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Francesca', 'Grigson', 'Hearn', '07-285-0196', 'fhearn60@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Tomkin', 'Gettens', 'Philliskirk', '32-393-0795', 'tphilliskirk61@t.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Kimmi', 'Apperley', 'Bew', '16-423-0226', 'kbew62@parallels.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Leandra', 'Adess', 'Hawke', '65-803-6297', 'lhawke63@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Wendall', 'Guyton', 'Balcombe', '67-902-0852', 'wbalcombe64@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Aldin', 'Veck', null, '46-475-7780', 'anehls65@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Nessy', 'Himsworth', 'Chippindale', '73-445-2590', 'nchippindale66@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Lebbie', 'Beyn', 'Sesons', '68-386-6989', 'lsesons67@phpbb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Clayborne', 'McCluin', null, '75-522-3687', 'cbewshire68@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Bobbie', 'Gawkes', 'Swadlin', '64-648-0350', 'bswadlin69@blog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Sander', 'Sherburn', 'Roomes', '10-784-0561', 'sroomes6a@ed.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Andrea', 'Baudry', 'Guidera', '31-214-1615', 'aguidera6b@imdb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Alisun', 'Keenleyside', 'MacEveley', '63-678-8516', 'amaceveley6c@t.co', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Melisent', 'Woolacott', 'Oakton', '56-723-7185', 'moakton6d@github.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Kelcy', 'Fearn', 'd'' Eye', '31-760-0800', 'kdeye6e@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Ailene', 'Rowntree', 'Catchpole', '20-116-8766', 'acatchpole6f@buzzfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Gerhardt', 'Vakhrushin', 'Boise', '97-701-7998', 'gboise6g@netscape.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Che', 'Jewett', 'Tobias', '95-738-5086', 'ctobias6h@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Land', 'Lansly', 'Sewart', '62-034-6535', 'lsewart6i@webeden.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Tierney', 'Mohring', null, '81-753-4036', 'tkenward6j@ask.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Gamaliel', 'McKain', 'Espino', '67-394-4066', 'gespino6k@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Blake', 'Girodin', 'Tellenbroker', '13-878-6695', 'btellenbroker6l@github.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Thalia', 'Alen', 'Ayrs', '98-551-5508', 'tayrs6m@digg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Joleen', 'Rosso', 'Ivanaev', '48-127-5528', 'jivanaev6n@google.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Feliks', 'Ginnety', 'Littell', '18-214-3383', 'flittell6o@apple.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Nowell', 'Wilds', null, '10-766-5715', 'npawlowicz6p@nbcnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Daveen', 'Dumphy', 'Welbelove', '95-868-5274', 'dwelbelove6q@mit.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Gael', 'Grier', 'Dudliston', '56-308-7462', 'gdudliston6r@domainmarket.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Aimee', 'Leveritt', 'Brandsma', '49-626-4653', 'abrandsma6s@hubpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Forester', 'Whipp', 'Glaister', '42-828-6322', 'fglaister6t@paginegialle.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Mariana', 'Charrington', null, '03-477-4369', 'mabarrow6u@bigcartel.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Allen', 'Hartin', 'Tenby', '36-916-8692', 'atenby6v@ustream.tv', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Jasun', 'Regardsoe', 'Brevetor', '15-809-6510', 'jbrevetor6w@scientificamerican.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Kylen', 'Urey', null, '89-344-1872', 'kduinbleton6x@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Jack', 'Sibly', null, '39-590-7044', 'jdobbie6y@merriam-webster.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Dominick', 'Pullen', 'Kann', '47-480-6106', 'dkann6z@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Lyndell', 'Bolino', 'Grogona', '44-844-3148', 'lgrogona70@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Maisey', 'Sadlier', null, '29-987-2020', 'mkearn71@github.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Jordan', 'Venning', 'Bodman', '61-377-2068', 'jbodman72@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Milly', 'Gipson', 'Morshead', '63-372-0351', 'mmorshead73@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Lacee', 'Milleton', 'Maud', '12-478-0842', 'lmaud74@people.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Storm', 'Zanelli', 'Offner', '13-839-1601', 'soffner75@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Tammy', 'Kroll', 'Kingsbury', '43-964-0541', 'tkingsbury76@rakuten.co.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Rodge', 'Rubes', 'Szymoni', '62-547-1914', 'rszymoni77@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Sabine', 'Eidelman', 'Swaile', '44-362-5403', 'sswaile78@jugem.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Chane', 'Tenniswood', 'Schimoni', '35-633-2300', 'cschimoni79@google.pl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Armin', 'Cotterill', 'Arnfield', '11-291-7487', 'aarnfield7a@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Fonsie', 'Flacknoe', 'Habergham', '05-148-8775', 'fhabergham7b@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Cammy', 'Manilow', null, '29-867-9450', 'cpusill7c@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Bren', 'Soffe', 'Margaritelli', '02-283-0585', 'bmargaritelli7d@hao123.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Merell', 'Callis', 'Kirkup', '68-403-9838', 'mkirkup7e@parallels.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Andree', 'Bantham', 'Santos', '51-779-2305', 'asantos7f@google.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Berton', 'Tadman', null, '10-782-8517', 'bgeorgelin7g@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Arly', 'Cardow', 'Mattersey', '49-266-4347', 'amattersey7h@hibu.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Kimmie', 'Ciccottio', 'De Filippi', '48-999-3657', 'kdefilippi7i@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Giana', 'Markushkin', 'Knolles-Green', '54-618-8074', 'gknollesgreen7j@indiegogo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Alyson', 'Duran', 'Rieflin', '12-484-7908', 'arieflin7k@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Hy', 'Bottelstone', 'Trodler', '16-529-4626', 'htrodler7l@spotify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Waiter', 'Bavester', null, '15-652-2907', 'wmoret7m@reddit.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Giuseppe', 'Hast', 'Brigstock', '84-541-4690', 'gbrigstock7n@theatlantic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Percival', 'Jiruch', 'Wallsam', '20-996-6599', 'pwallsam7o@theglobeandmail.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Brit', 'Need', 'Chung', '44-508-3653', 'bchung7p@indiatimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Fanechka', 'Wilkison', 'Dukelow', '03-878-0224', 'fdukelow7q@youku.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Winifred', 'Hammonds', 'Tampion', '75-325-3901', 'wtampion7r@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Loria', 'Nesbitt', 'Eisak', '90-023-0571', 'leisak7s@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Titos', 'Markey', 'Lorie', '27-947-1466', 'tlorie7t@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Ariel', 'Avison', null, '19-445-7311', 'achallener7u@blogger.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Guthry', 'Adnams', 'Janney', '69-802-4044', 'gjanney7v@squarespace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Thor', 'Castellucci', 'Founds', '51-330-8813', 'tfounds7w@friendfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Fanchette', 'Kaindl', 'Hutchins', '56-110-3854', 'fhutchins7x@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Cart', 'Shimuk', 'Hartigan', '87-674-2855', 'chartigan7y@wired.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Edouard', 'Aldrick', 'Mettricke', '39-946-1321', 'emettricke7z@miibeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Carmita', 'Comrie', 'Emmert', '82-939-4760', 'cemmert80@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Jan', 'Darling', 'Oloshin', '04-869-4498', 'joloshin81@nps.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Caterina', 'Leates', null, '94-285-4028', 'cberndtssen82@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Karrah', 'Petley', 'Lepick', '22-497-2741', 'klepick83@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Dorree', 'De Micoli', 'De Brett', '67-443-5199', 'ddebrett84@1688.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Doroteya', 'Bonass', 'Lomond', '83-510-3961', 'dlomond85@desdev.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'Marcellina', 'Kubat', null, '81-569-4529', 'mhebden86@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Boonie', 'Stodit', 'Matanin', '62-883-2592', 'bmatanin87@acquirethisname.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Mayne', 'Basketfield', null, '85-509-7679', 'mhabert88@geocities.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Margalit', 'Pedgrift', 'Gudahy', '89-517-2650', 'mgudahy89@typepad.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Chastity', 'Sangster', null, '71-079-7426', 'csowerbutts8a@washington.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Cherilyn', 'Gavrielli', 'Ponsford', '00-187-4356', 'cponsford8b@dagondesign.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Jerrilyn', 'Button', null, '94-044-1998', 'jmoxson8c@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Rubie', 'Geockle', 'Guiu', '32-607-9409', 'rguiu8d@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Francisca', 'Northill', 'Riditch', '39-895-0086', 'friditch8e@reference.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Gertrudis', 'Vere', 'Harriman', '71-431-8597', 'gharriman8f@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Elana', 'Sharnock', 'Selbach', '72-912-7234', 'eselbach8g@mtv.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Hilde', 'Woodington', 'Klesse', '24-531-8504', 'hklesse8h@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Mireille', 'Sibbe', 'Caccavari', '03-337-6031', 'mcaccavari8i@cbslocal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Dania', 'Roddick', null, '63-211-3686', 'dgilbert8j@xinhuanet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Erna', 'Gianulli', 'Lince', '12-987-2595', 'elince8k@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Kelwin', 'Piller', 'Spybey', '00-334-1524', 'kspybey8l@chronoengine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Adelaida', 'Yoxen', 'Shellsheere', '30-916-3525', 'ashellsheere8m@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Stanislaw', 'Folcarelli', 'Barhem', '60-196-4680', 'sbarhem8n@go.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Gifford', 'Kocher', null, '72-027-9519', 'glagde8o@tripod.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Pearce', 'Heffer', 'Corter', '05-858-9811', 'pcorter8p@live.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Hilliary', 'Guerri', 'Redhills', '73-441-6369', 'hredhills8q@bandcamp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Patsy', 'Dibble', 'Bostock', '02-124-6545', 'pbostock8r@soundcloud.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Theressa', 'Mangin', null, '81-934-1332', 'tghidoni8s@forbes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Windy', 'Leguey', 'Coverdill', '15-664-1964', 'wcoverdill8t@arstechnica.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Evin', 'Hayesman', 'Seeler', '61-694-7171', 'eseeler8u@smh.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Willa', 'Wasiela', 'Vankeev', '16-473-1663', 'wvankeev8v@ameblo.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Jemie', 'Esseby', 'Bartolini', '13-238-9054', 'jbartolini8w@gov.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Abe', 'Dimmack', 'Davy', '82-079-8277', 'adavy8x@admin.ch', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Mirelle', 'Gooley', 'Trotter', '67-351-3726', 'mtrotter8y@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Lionello', 'Roxbee', 'Carbert', '44-016-0745', 'lcarbert8z@constantcontact.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Damien', 'Serchwell', 'Gleed', '73-788-6225', 'dgleed90@de.vu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Windham', 'Chadney', 'Braden', '32-589-4119', 'wbraden91@mediafire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Emili', 'Huncote', null, '92-111-2078', 'eogiany92@scientificamerican.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Cyb', 'Del Checolo', 'Brent', '94-934-2962', 'cbrent93@cnbc.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Antonin', 'Sammons', 'Peirazzi', '17-034-2483', 'apeirazzi94@smh.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Pavel', 'Cordier', 'Scandwright', '45-920-3428', 'pscandwright95@blogs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Millie', 'Kilmurray', 'Campes', '44-902-3936', 'mcampes96@archive.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Kenon', 'Vlies', null, '20-034-8567', 'kphin97@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Tyne', 'Beevis', 'Wabey', '35-036-5596', 'twabey98@printfriendly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Auria', 'Shrive', 'Duley', '71-323-9938', 'aduley99@gmpg.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Gayle', 'Monkeman', 'Coltman', '48-312-5993', 'gcoltman9a@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Celinda', 'Serle', 'Jewks', '23-986-9425', 'cjewks9b@sourceforge.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Ernaline', 'Pendre', 'Schrir', '53-362-1952', 'eschrir9c@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Craggie', 'Butten', 'Trinder', '03-094-8954', 'ctrinder9d@chicagotribune.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Rodney', 'Palumbo', 'Wrinch', '09-827-9390', 'rwrinch9e@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Yalonda', 'Zupo', 'Palphramand', '30-793-5543', 'ypalphramand9f@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Alexia', 'Brownstein', 'Saunder', '03-511-7165', 'asaunder9g@feedburner.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Windy', 'Laver', 'Burnall', '63-246-6207', 'wburnall9h@sfgate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Ransom', 'Giddens', 'Seebright', '97-770-8958', 'rseebright9i@flavors.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Emalia', 'Brownlow', null, '30-451-4653', 'edalgarnowch9j@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Ferdie', 'Waterdrinker', 'Broz', '67-333-8216', 'fbroz9k@tmall.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Nerissa', 'Stolberger', 'Gruszecki', '05-608-0653', 'ngruszecki9l@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Chaddie', 'Raffin', 'Spikeings', '91-030-1236', 'cspikeings9m@irs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Shelley', 'Watmore', 'Attrill', '64-190-5855', 'sattrill9n@go.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Perice', 'Delgua', 'Bittany', '84-490-2444', 'pbittany9o@trellian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Everett', 'Barkus', 'Orteaux', '25-885-9114', 'eorteaux9p@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Riane', 'Aprahamian', null, '37-796-0592', 'rerskinesandys9q@reddit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Rubina', 'Gulvin', null, '67-808-5552', 'rstiggles9r@irs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Beverley', 'Rosenwald', 'Spurriar', '53-040-9068', 'bspurriar9s@salon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Charlean', 'Spinetti', 'Kleinlerer', '55-614-6308', 'ckleinlerer9t@de.vu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Florella', 'Jarrette', 'Heathfield', '32-929-4362', 'fheathfield9u@berkeley.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Culley', 'Elgey', 'Jahnke', '89-206-5172', 'cjahnke9v@eepurl.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Theressa', 'Colegate', 'Cockshtt', '10-835-1366', 'tcockshtt9w@hc360.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Pembroke', 'Canto', 'Cruft', '54-857-8263', 'pcruft9x@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Andrus', 'Attrey', 'Buglar', '39-705-8497', 'abuglar9y@wikispaces.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Hayley', 'Chasteau', 'Lapree', '13-401-1587', 'hlapree9z@wordpress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Garnet', 'Dearle-Palser', 'Chalkly', '16-035-9691', 'gchalklya0@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Daphene', 'Cronshaw', 'Sandercock', '23-496-9094', 'dsandercocka1@i2i.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Cris', 'Droghan', 'McKern', '38-657-8073', 'cmckerna2@alibaba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Theo', 'Gunderson', null, '62-302-8369', 'tjosefsena3@un.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Smith', 'Muck', null, '85-731-0170', 'solivaria4@ycombinator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Robbert', 'Harburtson', null, '83-897-9525', 'rcanhama5@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Colan', 'Meeland', 'Bengtson', '10-468-5209', 'cbengtsona6@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Mariette', 'Filip', 'Toping', '84-285-7832', 'mtopinga7@1und1.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Agathe', 'Port', null, '25-163-4345', 'aclementsa8@vimeo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Curt', 'Ironside', 'Camblin', '92-461-4216', 'ccamblina9@google.com.br', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Caressa', 'Pirolini', 'Primrose', '66-544-2174', 'cprimroseaa@rambler.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Merrilee', 'Inglese', 'Alonso', '91-257-9642', 'malonsoab@sciencedaily.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Geoffry', 'Giraudo', 'Darinton', '91-607-0635', 'gdarintonac@seesaa.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Mahmoud', 'Garry', 'Spon', '07-001-3224', 'msponad@hao123.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Fernanda', 'Prium', null, '65-465-0779', 'fcullaghae@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'Brier', 'Spinley', 'Baise', '51-179-6300', 'bbaiseaf@amazon.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Lydon', 'Ladson', 'De Giovanni', '11-568-3092', 'ldegiovanniag@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Sonni', 'Schult', 'Dymock', '70-452-8558', 'sdymockah@people.com.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Cristobal', 'Hadwin', 'Jellings', '08-175-7707', 'cjellingsai@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Leticia', 'Guarnier', 'Garlinge', '55-949-8988', 'lgarlingeaj@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Zelig', 'Craigheid', 'Erricker', '36-290-9634', 'zerrickerak@wisc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Maurizia', 'Mallord', 'Gouldbourn', '34-585-3892', 'mgouldbournal@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Maison', 'Endicott', 'Stannislawski', '88-966-6948', 'mstannislawskiam@sogou.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Giusto', 'Motion', null, '73-726-9275', 'gfleetwoodan@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Barb', 'Le Strange', 'Garry', '75-301-4245', 'bgarryao@taobao.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Joane', 'Hooban', null, '68-801-9297', 'jkiddyeap@vistaprint.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'De', 'Legrand', 'Label', '83-601-7825', 'dlabelaq@who.int', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Alexandre', 'Gabbitis', 'Yvon', '41-628-8017', 'ayvonar@weather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Kordula', 'Brickett', 'Bernhardt', '38-028-0179', 'kbernhardtas@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Faulkner', 'Laydel', 'Kimbrey', '19-151-9378', 'fkimbreyat@google.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Caryl', 'Mattsson', 'Frid', '90-223-5196', 'cfridau@dailymail.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Adrien', 'Mixon', 'Mantrup', '92-447-9501', 'amantrupav@exblog.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Jessie', 'Kilfeder', 'Loidl', '94-162-0392', 'jloidlaw@acquirethisname.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Bernie', 'Garbutt', 'Veschi', '68-469-3199', 'bveschiax@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Cyb', 'Izzat', 'Bloggett', '76-059-9713', 'cbloggettay@furl.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Granthem', 'Gellett', 'Piken', '22-169-8461', 'gpikenaz@etsy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Virgil', 'Peete', null, '55-962-4189', 'vderringtonb0@patch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Helen-elizabeth', 'Currier', 'Buff', '11-912-8751', 'hbuffb1@cafepress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Ana', 'Craine', 'Dana', '22-692-7307', 'adanab2@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Abigale', 'Heathcote', 'Birwhistle', '45-312-2715', 'abirwhistleb3@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Rufus', 'Joseff', null, '21-375-8517', 'rmaceb4@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Byram', 'Ivashnikov', 'Ramelot', '04-447-6332', 'bramelotb5@alibaba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Dottie', 'Tesoe', 'Riddick', '34-673-3971', 'driddickb6@cnbc.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Dalli', 'Berrington', 'Zimek', '59-340-3423', 'dzimekb7@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Nat', 'Guiden', null, '36-110-8631', 'nmorlandb8@odnoklassniki.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Henry', 'Rupke', 'Bubbings', '27-322-3894', 'hbubbingsb9@mozilla.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Cassie', 'Raddenbury', null, '91-131-9559', 'crudgleyba@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Raphael', 'Greiser', 'Leeson', '34-718-5622', 'rleesonbb@vkontakte.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Margaretta', 'Traves', 'Laweles', '48-470-7356', 'mlawelesbc@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Malory', 'Blizard', null, '94-662-1465', 'mcurrierbd@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Simonette', 'Lymer', 'Omond', '94-718-3451', 'somondbe@sohu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Derk', 'McGlue', 'MacKeeg', '90-550-3464', 'dmackeegbf@bizjournals.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Gale', 'Mulliss', 'McNickle', '49-471-6994', 'gmcnicklebg@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Huntington', 'Bullcock', 'Dunnett', '14-275-4712', 'hdunnettbh@google.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Isadore', 'Kent', 'Cartmer', '72-349-1325', 'icartmerbi@yale.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Gianina', 'O'' Clovan', 'Normandale', '18-301-1562', 'gnormandalebj@state.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Dorri', 'Turrill', 'Messham', '47-325-9443', 'dmesshambk@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Brock', 'Kike', null, '14-245-6808', 'bcriellybl@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Jeffy', 'Sagrott', 'Notman', '37-799-9765', 'jnotmanbm@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Zebadiah', 'Tudhope', null, '82-016-5528', 'zbursnallbn@wiley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Lenore', 'Courson', 'Feben', '58-213-1920', 'lfebenbo@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Tabbie', 'Plumbley', 'Starsmeare', '03-121-7541', 'tstarsmearebp@cdbaby.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Pattie', 'Bowfin', 'Cornelleau', '87-127-5250', 'pcornelleaubq@google.com.hk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Libbi', 'List', 'Calvert', '90-478-7471', 'lcalvertbr@linkedin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Camellia', 'Penley', 'Barnbrook', '29-625-1571', 'cbarnbrookbs@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Gaspard', 'Tilbury', 'Horlock', '27-625-0003', 'ghorlockbt@china.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Rosie', 'Withers', 'Pipworth', '84-278-6247', 'rpipworthbu@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Barby', 'McGennis', 'Dartnall', '51-277-4037', 'bdartnallbv@vk.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Diannne', 'Stannion', null, '42-274-0339', 'dwadhambw@amazon.co.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Kilian', 'Loudiane', 'Dannett', '52-513-2317', 'kdannettbx@bbb.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Shela', 'Cavalier', 'Clears', '57-292-6428', 'sclearsby@bloomberg.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Bink', 'Friese', null, '11-041-3411', 'bfraschettibz@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Sydney', 'Braunle', 'Blenkensop', '58-332-5064', 'sblenkensopc0@myspace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Skipper', 'Jakobssen', 'McLaughlan', '05-229-1205', 'smclaughlanc1@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Bill', 'Tregear', 'Haslehurst', '38-554-4816', 'bhaslehurstc2@google.nl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Randy', 'Bruggen', null, '89-032-5834', 'rbockec3@ow.ly', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Alexia', 'Varey', 'Dulany', '28-162-9442', 'adulanyc4@moonfruit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Brocky', 'Kilford', null, '40-218-8114', 'bmazdonc5@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Stevana', 'Chilcott', null, '26-498-3018', 'swoodfordc6@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Shaw', 'Britnell', 'Worswick', '62-672-0156', 'sworswickc7@nba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Iris', 'Graysmark', 'Band', '25-603-2804', 'ibandc8@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Sarge', 'De Lorenzo', 'Carnall', '98-380-8597', 'scarnallc9@blogspot.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Crissie', 'Slemming', 'Wildber', '37-083-7119', 'cwildberca@opensource.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Fionna', 'Hobbema', 'Ceschini', '10-634-9491', 'fceschinicb@webnode.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Dimitry', 'Blaydes', 'Lohan', '78-819-7747', 'dlohancc@over-blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Janine', 'Leuren', 'Moughton', '32-294-4972', 'jmoughtoncd@mozilla.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Kellen', 'Crass', 'Doneld', '48-154-2961', 'kdoneldce@ifeng.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Bill', 'Lund', 'Featenby', '83-438-8400', 'bfeatenbycf@acquirethisname.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Roch', 'Caldeiro', 'Waine', '15-557-0089', 'rwainecg@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Pip', 'Linkin', 'Gutherson', '90-137-1240', 'pguthersonch@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Harlin', 'Hearons', null, '50-553-5801', 'hganleyci@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Gun', 'Styche', 'Derbyshire', '75-613-9220', 'gderbyshirecj@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Hetty', 'Soan', 'Blaise', '54-521-7156', 'hblaiseck@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Austin', 'Hedin', 'Blondell', '40-113-6941', 'ablondellcl@pinterest.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Haze', 'Maunders', 'Wickham', '08-107-1965', 'hwickhamcm@jiathis.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Graig', 'Castleton', null, '22-537-5810', 'gdreghorncn@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Kimberlyn', 'Lynock', null, '82-098-5318', 'kmadeleyco@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Bernhard', 'Gregs', 'Corkill', '56-114-0971', 'bcorkillcp@angelfire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Pia', 'Siddle', 'Ruby', '17-104-7946', 'prubycq@hubpages.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Nolly', 'Nicklen', 'Chesworth', '11-774-7207', 'nchesworthcr@over-blog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Lena', 'Sabie', 'Coch', '00-670-7171', 'lcochcs@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Amil', 'Clemmens', 'Waith', '14-255-1734', 'awaithct@aboutads.info', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Nero', 'Tattam', null, '26-472-7561', 'nrickettcu@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Jud', 'Robertet', 'Reedy', '65-511-4588', 'jreedycv@blogs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Nadia', 'Ouslem', 'Harmant', '88-642-8585', 'nharmantcw@washingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Marshal', 'Ashley', 'Philpot', '86-892-3920', 'mphilpotcx@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Shurlock', 'Goricke', 'Sherman', '44-231-1286', 'sshermancy@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Dominique', 'Thorpe', null, '33-294-7023', 'drillstonecz@opera.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Christy', 'Megahey', null, '43-620-7848', 'cgrigoired0@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Cirilo', 'Marti', 'Willwood', '78-761-6600', 'cwillwoodd1@nytimes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Marissa', 'Belchamp', 'Huton', '89-974-9829', 'mhutond2@alexa.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Jessie', 'Hutton', null, '56-939-8079', 'jheintzd3@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Haven', 'Bigby', 'Crosgrove', '39-817-3515', 'hcrosgroved4@hatena.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Vannie', 'Roark', 'Ferrieroi', '61-154-8962', 'vferrieroid5@bizjournals.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Nancey', 'Soames', null, '61-888-6848', 'ninkled6@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Karel', 'Aronsohn', 'Bastie', '23-571-4667', 'kbastied7@nationalgeographic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Lemmy', 'Kepling', null, '08-268-7536', 'ldurtnalld8@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Traver', 'Cleve', 'Castrillo', '48-956-0680', 'tcastrillod9@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Kippy', 'Roff', 'Popelay', '60-204-7649', 'kpopelayda@boston.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Cecilio', 'Tall', 'Brownsmith', '10-006-6702', 'cbrownsmithdb@bbc.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Wilbert', 'Buy', 'Tulley', '56-748-6557', 'wtulleydc@netlog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Lynna', 'Drakeford', 'Torr', '78-225-3413', 'ltorrdd@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Christyna', 'Finlay', 'Bolver', '50-334-2059', 'cbolverde@apple.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Melisent', 'de Mullett', 'Crommett', '41-663-2872', 'mcrommettdf@xrea.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Elroy', 'Muirden', 'Rolse', '53-274-7981', 'erolsedg@springer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Eachelle', 'Greenshiels', 'Scholtz', '10-135-9841', 'escholtzdh@gnu.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Anica', 'Van Merwe', 'Hulburd', '06-656-6504', 'ahulburddi@bloomberg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Lela', 'Hazelden', 'Dosdell', '23-891-8217', 'ldosdelldj@vistaprint.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Nickolai', 'Dewberry', 'Exroll', '75-760-2276', 'nexrolldk@oakley.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Elinore', 'Pendrid', 'Athersmith', '89-295-6642', 'eathersmithdl@theatlantic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Jillian', 'Sappson', 'Claque', '50-755-8681', 'jclaquedm@jugem.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Flin', 'Fitchell', null, '73-705-4515', 'fbrysondn@google.pl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Niki', 'Kenrack', null, '11-751-7809', 'nstelledo@pen.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Isa', 'Folger', 'Vasile', '29-390-8707', 'ivasiledp@hugedomains.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Jorrie', 'Kelcher', 'Alpin', '54-799-1826', 'jalpindq@com.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Guntar', 'Eloi', 'Lyvon', '63-141-5361', 'glyvondr@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Saunders', 'Stovin', null, '88-256-0996', 'sproudlockds@reference.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Lauraine', 'Plaskett', 'Brummell', '67-540-5863', 'lbrummelldt@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Molly', 'Camplin', null, '39-156-6067', 'mollerearnshawdu@studiopress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Colet', 'Friedank', 'Ranklin', '42-470-6169', 'cranklindv@google.pl', null);
