insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (1, 'B95069', 'Alfred H. Baumann Free Public Library (West Paterson)', '582 Sunnyside Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (2, 'B28288', 'Anthony Pio Costa Memorial Library (Fairfield)', '082 Oxford Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (3, 'B97381', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '63310 Ridgeview Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (4, 'B21572', 'Otto Bruyns Public Library (Northfield)', '75745 Pawling Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (5, 'B92785', 'Carney’s Point Public Library (Penns Grove)', '57 Prairie Rose Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (6, 'B74128', 'Clarence Dillon Public Library (Bedminster Far Hills)', '0083 Holy Cross Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (7, 'B10160', 'William E. Dermody Public Library (Carlstadt)', '264 Lawn Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (8, 'B91812', 'Clarence Dillon Public Library (Bedminster Far Hills)', '00261 Manitowish Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (9, 'B25235', 'Dixon Homestead Library (Dumont)', '11670 Buell Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (10, 'B33998', 'Dowdell Library of South Amboy (South Amboy)', '46387 Ridgeway Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (11, 'B88822', 'Dwight D. Eisenhower Library (Totowa)', '5623 Bowman Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (12, 'B16641', 'Marie Fleche Memorial Library (Berlin)', '5 Meadow Valley Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (13, 'B58893', 'Franklin Township Free Public Library (Gloucester)', '45 Pawling Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (14, 'B05350', 'Franklin Township Free Public Library (Somerset)', '73041 Sunfield Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (15, 'B13839', 'Free Public Library of Audubon (Audubon)', '4 Clarendon Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (16, 'B42984', 'Free PL of The Borough of Pompton Lakes (Pompton Lakes)', '3 Karstens Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (17, 'B87306', 'Gill Memorial Library (Paulsboro)', '82486 Gateway Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (18, 'B73772', 'Margaret E. Heggan Free PL (Washington Twp Gloucester)', '641 Golf View Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (19, 'B91220', 'Dixon Homestead Library (Dumont)', '4970 Shelley Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (20, 'B01266', 'James H. Johnson Memorial Library (Deptford)', '12 Carioca Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (21, 'B77165', 'Johnson Public Library (Hackensack)', '8233 Vahlen Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (22, 'B69370', 'James H. Johnson Memorial Library (Deptford)', '064 Huxley Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (23, 'B86016', 'John F. Kennedy Memorial Library (Wallington)', '2 Maple Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (24, 'B70766', 'Joint Free Public Library of the Chathams (Chatham)', '1 Hanover Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (25, 'B24485', 'Joint Free PL of Morristown & Morris Twp (Morristown-Morris Twp)', '487 Maple Wood Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (26, 'B09271', 'Sally Stretch Keen Memorial Library (Vincentown)', '20 7th Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (27, 'B69876', 'John F. Kennedy Memorial Library (Wallington)', '0102 Dryden Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (28, 'B24636', 'Lee Memorial Library (Allendale)', '8354 Moulton Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (29, 'B93617', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '2 Russell Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (30, 'B57408', 'Margare E. Heggan Free PL (Washington Twp Gloucester)', '39422 Lighthouse Bay Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (31, 'B99075', 'Marie Fleche Memorial Library (Berlin)', '6534 Westport Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (32, 'B24025', 'Maurice M. Pine Free Public Library (Fair Lawn)', '147 Maple Wood Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (33, 'B19830', 'McCowan Memorial Library (Pitman)', '8 Jana Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (34, 'B14451', 'Monroe Township Free Public Library (Gloucester Co)', '2 Eastlawn Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (35, 'B59276', 'Monroe Township Public Library (Middlesex Co.)', '936 Porter Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (36, 'B50196', 'Oceanic Free Library (Rumson)', '64 Magdeline Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (37, 'B47939', 'Otto Bruyns Public Library (Northfield)', '72674 Judy Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (38, 'B23673', 'Maurice M. Pine Free Public Library (Fair Lawn)', '6886 Eastlawn Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (39, 'B29758', 'Worth Pinkham Memorial Library (Ho-Ho-Kus)', '0 Armistice Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (40, 'B47141', 'Anthony Pio Costa Memorial Library (Fairfield)', '0688 Riverside Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (41, 'B42552', 'Ridgefield Free Public Library (Ridgefield)', '54 Golf Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (42, 'B13091', 'Ridgefield Park Free Public Library (Ridgefield Park)', '0 Helena Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (43, 'B22783', 'Ruth L. Rockwood Memorial Library (Livingston)', '60007 Eliot Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (44, 'B66865', 'Sally Stretch Keen Memorial Library (Vincentown)', '509 Kinsman Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (45, 'B99008', 'Union Free Public Library (Friberger Park', '51 Emmet Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (46, 'B65085', ' Union NJ)', '0 Farragut Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (47, 'B90176', 'Veteran’s Memorial Library (Roselle Park)', '36799 Gina Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (48, 'B75663', 'W.H. Walters Free Public Library (Alpha)', '2531 Vermont Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (49, 'B76538', 'Wanaque Borough Free Public Library', '6 Upham Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (50, 'B77963', 'Washington Public Library (Washington Boro/Warren Co)', '40528 Gerald Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (51, 'B80039', 'Washington Twp Free Public Library (Long Valley/Morris Co)', '0017 Oxford Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (52, 'B80821', 'Washington Twp Public Library (Westwood/Bergen Co)', '174 Linden Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (53, 'B34783', 'Whippanong Library Association (Whippany /Hanover Twp)', '37 Corben Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (54, 'B64234', 'William E. Dermody Public Library (Carlstadt)', '0763 Loftsgordon Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (55, 'B47710', 'Wood-Ridge Memorial Library', '8 Anniversary Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (56, 'B45141', 'Woodstown-Pilesgrove Library', '1144 Russell Way');
