drop table regular;
drop table oyente_asignatura;
drop table asignatura;
drop table oyente;
drop table estudiante;
drop index asig_asignatura_requerida_ix;
drop index estudiante_num_cuenta_ix;
drop sequence seq_estudiante;
drop view v_estudiante;